In [6]:
import pandas as pd

df=pd.read_csv(
    "../data/GSE2034_series_matrix.txt.gz",
    sep='\t',
    comment='!',
    index_col=0,
    compression='gzip'
)
print(df.shape)
df.head()

(22283, 286)

,GSM36777,GSM36778,GSM36779,GSM36780,GSM36781,GSM36782,GSM36783,GSM36784,GSM36785,GSM36786,...,GSM37053,GSM37054,GSM37055,GSM37056,GSM37057,GSM37058,GSM37059,GSM37060,GSM37061,GSM37062
ID_REF,,,,,,,,,,,,,,,,,,,,,
1007_s_at,3848.1,6520.9,5285.7,4043.7,4263.6,2949.8,5498.9,3863.1,3370.4,3991.9,...,4058.2,4017.6,2841.0,2914.2,3681.0,3066.9,2773.0,2984.3,3540.0,2620.0
1053_at,228.9,112.5,178.4,398.7,417.7,221.2,280.4,198.2,304.7,198.2,...,183.4,356.1,234.6,169.4,94.5,265.5,209.8,160.0,285.7,180.5
117_at,213.1,189.8,269.7,312.4,327.1,225.0,243.5,244.4,348.5,185.3,...,326.6,234.9,369.6,149.5,236.4,347.9,226.7,252.9,135.1,191.8
121_at,1009.4,2083.3,1203.4,1104.4,1043.3,1117.6,1085.4,1423.1,1196.4,993.3,...,1041.3,1195.6,751.5,1117.8,1022.4,1127.4,1071.8,1178.5,1256.7,1284.6
1255_g_at,31.8,145.8,42.5,108.2,69.2,47.4,84.3,102.0,22.8,86.3,...,143.5,32.7,62.6,43.0,100.5,47.0,45.1,146.3,75.9,87.4

In [7]:
df_t=df.T
print(df_t.shape)
df_t.head()

(286, 22283)

ID_REF,1007_s_at,1053_at,117_at,121_at,1255_g_at,1294_at,1316_at,1320_at,1405_i_at,1431_at,...,AFFX-r2-Hs28SrRNA-5_at,AFFX-r2-Hs28SrRNA-M_at,AFFX-r2-P1-cre-3_at,AFFX-r2-P1-cre-5_at,AFFX-ThrX-3_at,AFFX-ThrX-5_at,AFFX-ThrX-M_at,AFFX-TrpnX-3_at,AFFX-TrpnX-5_at,AFFX-TrpnX-M_at
GSM36777,3848.1,228.9,213.1,1009.4,31.8,551.5,176.7,11.9,309.3,49.9,...,619.9,661.5,33168.9,25644.4,11.1,9.2,25.0,4.2,7.0,10.0
GSM36778,6520.9,112.5,189.8,2083.3,145.8,802.8,278.4,28.3,449.0,122.9,...,511.3,716.1,54401.4,40720.0,17.1,62.0,21.4,9.3,11.2,15.7
GSM36779,5285.7,178.4,269.7,1203.4,42.5,557.5,183.3,56.4,101.9,85.9,...,1618.4,1189.3,61244.1,50878.7,6.4,8.4,7.4,7.1,64.0,4.1
GSM36780,4043.7,398.7,312.4,1104.4,108.2,568.5,187.7,42.1,899.1,90.7,...,780.5,801.1,62292.1,46870.8,13.5,10.8,16.0,4.6,12.2,7.3
GSM36781,4263.6,417.7,327.1,1043.3,69.2,653.2,185.8,21.8,3629.3,96.0,...,276.0,191.1,57295.1,40847.1,19.8,30.5,22.1,7.3,5.5,11.6

In [12]:
import gzip
from io import StringIO

with gzip.open("../data/GPL96.annot.gz", 'rt') as f:
    lines = f.readlines()

# Find the line that says the real table starts, and where it ends
start = next(i for i, l in enumerate(lines) if l.startswith('!platform_table_begin')) + 1
end = next(i for i, l in enumerate(lines) if l.startswith('!platform_table_end'))

table_text = ''.join(lines[start:end])
annot = pd.read_csv(StringIO(table_text), sep='\t', low_memory=False)

print(annot.shape)
annot.head()

(22283, 21)

,ID,Gene title,Gene symbol,Gene ID,UniGene title,UniGene symbol,UniGene ID,Nucleotide Title,GI,GenBank Accession,...,Platform_ORF,Platform_SPOTID,Chromosome location,Chromosome annotation,GO:Function,GO:Process,GO:Component,GO:Function ID,GO:Process ID,GO:Component ID
0,1007_s_at,microRNA 4640///discoidin domain receptor tyro...,MIR4640///DDR1,100616237///780,NaN,NaN,NaN,"Human receptor tyrosine kinase DDR gene, compl...",1753221.0,U48705,...,NaN,NaN,6p21.3,"Chromosome 6, NC_000006.12 (30890883..30890972...",ATP binding///collagen binding///collagen bind...,branching involved in mammary gland duct morph...,basolateral plasma membrane///extracellular ex...,GO:0005524///GO:0005518///GO:0005518///GO:0046...,GO:0060444///GO:0007155///GO:0038063///GO:0038...,GO:0016323///GO:0070062///GO:0005615///GO:0005...
1,1053_at,replication factor C subunit 2,RFC2,5982,NaN,NaN,NaN,"Human replication factor C, 40-kDa subunit (A1...",1590810.0,M87338,...,NaN,NaN,7q11.23,"Chromosome 7, NC_000007.14 (74231502..74254458...",ATP binding///contributes_to DNA clamp loader ...,"DNA damage response, detection of DNA damage//...",Ctf18 RFC-like complex///DNA replication facto...,GO:0005524///contributes_to GO:0003689///GO:00...,GO:0042769///GO:0006260///GO:0070987///GO:0042...,GO:0031390///GO:0005663///GO:0005654
2,117_at,heat shock protein family A (Hsp70) member 6,HSPA6,3310,NaN,NaN,NaN,Human heat-shock protein HSP70B' gene,35221.0,X51757,...,NaN,NaN,1q23,"Chromosome 1, NC_000001.11 (161524540..161526897)","ATP binding///ATPase activity, coupled///enzym...",NOT cellular heat acclimation///cellular respo...,colocalizes_with COP9 signalosome///blood micr...,GO:0005524///GO:0042623///GO:0019899///GO:0031...,NOT GO:0070370///GO:0034605///GO:0034605///GO:...,colocalizes_with GO:0008180///GO:0072562///GO:...
3,121_at,paired box 8,PAX8,7849,NaN,NaN,NaN,H.sapiens Pax8 mRNA,38425.0,X69699,...,NaN,NaN,2q13,"Chromosome 2, NC_000002.12 (113215997..1132789...",DNA binding///DNA binding///RNA polymerase II ...,anatomical structure morphogenesis///branching...,nucleoplasm///nucleoplasm///nucleus,GO:0003677///GO:0003677///GO:0000978///GO:0000...,GO:0009653///GO:0001658///GO:0071371///GO:0007...,GO:0005654///GO:0005654///GO:0005634
4,1255_g_at,guanylate cyclase activator 1A,GUCA1A,2978,NaN,NaN,NaN,Homo sapiens guanylate cyclase activating prot...,623404.0,L36861,...,NaN,NaN,6p21.1,"Chromosome 6, NC_000006.12 (42155377..42180083)",calcium ion binding///calcium sensitive guanyl...,cellular response to calcium ion///phototransd...,photoreceptor disc membrane///photoreceptor in...,GO:0005509///GO:0008048///GO:0030249,GO:0071277///GO:0007602///GO:0031284///GO:0022...,GO:0097381///GO:0001917///GO:0005886

In [13]:
esr1_rows=annot[annot['Gene symbol']=='ESR1']
esr1_rows

,ID,Gene title,Gene symbol,Gene ID,UniGene title,UniGene symbol,UniGene ID,Nucleotide Title,GI,GenBank Accession,...,Platform_ORF,Platform_SPOTID,Chromosome location,Chromosome annotation,GO:Function,GO:Process,GO:Component,GO:Function ID,GO:Process ID,GO:Component ID
4751,205225_at,estrogen receptor 1,ESR1,2099,NaN,NaN,NaN,"Homo sapiens estrogen receptor 1 (ESR1), trans...",170295798.0,NM_000125,...,NaN,NaN,6q25.1,"Chromosome 6, NC_000006.12 (151654148..152103274)",ATPase binding///RNA polymerase II core promot...,Sertoli cell development///Sertoli cell prolif...,Golgi apparatus///T-tubule///cytoplasm///integ...,GO:0051117///GO:0000978///GO:0038052///GO:0038...,GO:0060009///GO:0060011///GO:0008209///GO:0001...,GO:0005794///GO:0030315///GO:0005737///GO:0016...
10670,211233_x_at,estrogen receptor 1,ESR1,2099,NaN,NaN,NaN,"Human estrogen receptor mRNA, complete cds",182192.0,M12674,...,NaN,NaN,6q25.1,"Chromosome 6, NC_000006.12 (151654148..152103274)",ATPase binding///RNA polymerase II core promot...,Sertoli cell development///Sertoli cell prolif...,Golgi apparatus///T-tubule///cytoplasm///integ...,GO:0051117///GO:0000978///GO:0038052///GO:0038...,GO:0060009///GO:0060011///GO:0008209///GO:0001...,GO:0005794///GO:0030315///GO:0005737///GO:0016...
10671,211234_x_at,estrogen receptor 1,ESR1,2099,NaN,NaN,NaN,"Homo sapiens estrogen receptor alpha mRNA, com...",11907834.0,AF258449,...,NaN,NaN,6q25.1,"Chromosome 6, NC_000006.12 (151654148..152103274)",ATPase binding///RNA polymerase II core promot...,Sertoli cell development///Sertoli cell prolif...,Golgi apparatus///T-tubule///cytoplasm///integ...,GO:0051117///GO:0000978///GO:0038052///GO:0038...,GO:0060009///GO:0060011///GO:0008209///GO:0001...,GO:0005794///GO:0030315///GO:0005737///GO:0016...
10672,211235_s_at,estrogen receptor 1,ESR1,2099,NaN,NaN,NaN,"Homo sapiens estrogen receptor alpha mRNA, com...",11907836.0,AF258450,...,NaN,NaN,6q25.1,"Chromosome 6, NC_000006.12 (151654148..152103274)",ATPase binding///RNA polymerase II core promot...,Sertoli cell development///Sertoli cell prolif...,Golgi apparatus///T-tubule///cytoplasm///integ...,GO:0051117///GO:0000978///GO:0038052///GO:0038...,GO:0060009///GO:0060011///GO:0008209///GO:0001...,GO:0005794///GO:0030315///GO:0005737///GO:0016...
11031,211627_x_at,estrogen receptor 1,ESR1,2099,NaN,NaN,NaN,Human estrogen receptor-related protein (varia...,182218.0,M69297,...,NaN,NaN,6q25.1,"Chromosome 6, NC_000006.12 (151654148..152103274)",ATPase binding///RNA polymerase II core promot...,Sertoli cell development///Sertoli cell prolif...,Golgi apparatus///T-tubule///cytoplasm///integ...,GO:0051117///GO:0000978///GO:0038052///GO:0038...,GO:0060009///GO:0060011///GO:0008209///GO:0001...,GO:0005794///GO:0030315///GO:0005737///GO:0016...
14923,215551_at,estrogen receptor 1,ESR1,2099,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,6q25.1,"Chromosome 6, NC_000006.12 (151654148..152103274)",ATPase binding///RNA polymerase II core promot...,Sertoli cell development///Sertoli cell prolif...,Golgi apparatus///T-tubule///cytoplasm///integ...,GO:0051117///GO:0000978///GO:0038052///GO:0038...,GO:0060009///GO:0060011///GO:0008209///GO:0001...,GO:0005794///GO:0030315///GO:0005737///GO:0016...
14924,215552_s_at,estrogen receptor 1,ESR1,2099,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,6q25.1,"Chromosome 6, NC_000006.12 (151654148..152103274)",ATPase binding///RNA polymerase II core promot...,Sertoli cell development///Sertoli cell prolif...,Golgi apparatus///T-tubule///cytoplasm///integ...,GO:0051117///GO:0000978///GO:0038052///GO:0038...,GO:0060009///GO:0060011///GO:0008209///GO:0001...,GO:0005794///GO:0030315///GO:0005737///GO:0016...
16529,217163_at,estrogen receptor 1,ESR1,2099,NaN,NaN,NaN,H.sapiens DNA for oestrogen receptor gene prom...,35159.0,X63118,...,NaN,NaN,6q25.1,"Chromosome 6, NC_000006.12 (151654148..152103274)",ATPase binding///RNA polymerase II core promot...,Sertoli cell development///Sertoli cell prolif...,Golgi apparatus///T-tubule///cytoplasm///integ...,GO:0051117///GO:0000978///GO:0038052///GO:0038...,GO:0060009///GO:0060011///GO:0008209///GO:0001...,GO:0005794///GO:0030315///GO:0005737///GO:0016...
16556,217190_x_at,estrogen receptor 1,ESR1,2099,NaN,NaN,NaN,"estrogen receptor {exon 6} [human, tamoxifen-r...",459362.0,S67777,...,NaN,NaN,6q25.1,"Chromosome 6, NC_000006.12 (151654148..152103274)",ATPase binding///RNA polymerase II core promot...,Sertoli cell development///Sertoli cell prolif...,Golgi apparatus///T-tubule///cytoplasm///integ...,GO:0051117///GO:0000978///GO:0038052///GO:0038...,GO:0060009///GO:0060011///GO:0008209///GO:0001...,GO:0005794///GO:0030315///GO:0005737///GO:0016...

In [16]:
Y=df_t['205225_at']


X=df_t.drop(columns=['205225_at', '211233_x_at'])

print("Y shape:", Y.shape)
print("X shape:", X.shape)

Y.head()

Y shape: (286,)
X shape: (286, 22281)

GSM36777    14608.6
GSM36778    13957.2
GSM36779     6885.9
GSM36780      306.7
GSM36781      472.2
Name: 205225_at, dtype: float64